[package]
name = "custom_api"
version = "0.1.0"
edition = "2021"

[lib]
name = "custom_api"
path = "src/lib.rs"

[dependencies]
chrono = { version = "0.4.23", features = ["serde"] }
serde = { verstion = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
