[package]
name = "custom_db"
version = "0.1.0"
edition = "2021"

[lib]
name = "custom_db"
path = "src/lib.rs"

[dependencies]
chrono = { version = "0.4.23", features = ["serde"] }
diesel = { version = "2.0.2", features = ["postgres", "r2d2", "chrono", "uuid"] }